#!/bin/bash
if [ "$UID" == "0" ]; then
    echo "this script must be run as a regular user"
    exit 7
fi

/usr/bin/gsettings set "org.gnome.desktop.lockdown" "disable-lock-screen" "true"
/usr/bin/gsettings set "org.gnome.desktop.screensaver" "lock-enabled" "false"
