#!/bin/bash
if ! [ -z "$1" ]; then
    echo "usage:"
    echo "remove-first-setup-user"
    exit 5
fi

if ! [ "$UID" == "0" ]; then
    echo "this script must be run with super user privileges"
    exit 6
fi

systemctl enable remove-first-setup-user.service
